spring.application.name=erp_back
spring.datasource.url=jdbc:${SGBD}://${DB_HOST}:${DB_PORT}/${DB_NAME}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

server.port=443
server.ssl.key-store=classpath:keystore.p12
server.ssl.key-store-password=${SSL_PASSWORD}
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=erp_iut

spring.mail.host=smtp.office365.com
spring.mail.port=587

mail.from=reiahoani.taero@etu.unilim.fr
mail.subject=Notification - IUT'xpress
mail.content=Bonjour,\n\nCeci est un mail automatique, veuillez ne pas répondre

spring.mail.username=reiahoani.taero@etu.unilim.fr
spring.mail.password=sM@$3r16

spring.mail.protocol=smtp
spring.mail.default-encoding=UTF-8

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000